publish = "dist"
command = "NODE_OPTIONS='--max_old_space_size=4096' npm run build"

[context.production.environment]
NUXT_ENV = "production" # Define variáveis de ambiente para produção

[context.deploy-preview]
command = "npm run build" # O comando de build para previews

memory = 3072